/** @file Re-exports `TX_*` aliases for legacy imports — canonical tokens live in `./app-form-styles`. */

export {
  APP_FORM_AMOUNT_PRIMARY_CLASS as TX_FORM_AMOUNT_PRIMARY_CLASS,
  APP_FORM_DESCRIPTION_CLASS as TX_FORM_DESCRIPTION_CLASS,
  APP_FORM_FIELD_CLASS as TX_FORM_FIELD_CLASS,
  APP_FORM_FIELDS_STACK_CLASS as TX_FORM_FIELDS_STACK_CLASS,
  APP_FORM_FOOTER_CLASS as TX_FORM_FOOTER_CLASS,
  APP_FORM_HEADER_CLASS as TX_FORM_HEADER_CLASS,
  APP_FORM_LABEL_CLASS as TX_FORM_LABEL_CLASS,
  APP_FORM_PANEL_CLASS as TX_FORM_PANEL_CLASS,
  APP_FORM_SECONDARY_BTN_CLASS as TX_FORM_SECONDARY_BTN_CLASS,
  APP_FORM_SELECT_CLASS as TX_FORM_SELECT_CLASS,
  APP_FORM_STACK_CLASS as TX_FORM_STACK_CLASS,
  APP_FORM_SUBMIT_CLASS as TX_FORM_SUBMIT_CLASS,
  APP_FORM_SWITCH_ROW_CLASS as TX_FORM_SWITCH_ROW_CLASS,
  APP_FORM_TITLE_CLASS as TX_FORM_TITLE_CLASS,
} from "./app-form-styles"
